/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RejectedRouteImport } from './routes/rejected'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PendingReviewRouteImport } from './routes/pending-review'
import { Route as CompleteProfileRouteImport } from './routes/complete-profile'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomsRoomIdRouteImport } from './routes/rooms.$roomId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RejectedRoute = RejectedRouteImport.update({
  id: '/rejected',
  path: '/rejected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingReviewRoute = PendingReviewRouteImport.update({
  id: '/pending-review',
  path: '/pending-review',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteProfileRoute = CompleteProfileRouteImport.update({
  id: '/complete-profile',
  path: '/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoomIdRoute = RoomsRoomIdRouteImport.update({
  id: '/rooms/$roomId',
  path: '/rooms/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/pending-review': typeof PendingReviewRoute
  '/profile': typeof ProfileRoute
  '/rejected': typeof RejectedRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/pending-review': typeof PendingReviewRoute
  '/profile': typeof ProfileRoute
  '/rejected': typeof RejectedRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/pending-review': typeof PendingReviewRoute
  '/profile': typeof ProfileRoute
  '/rejected': typeof RejectedRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/complete-profile'
    | '/pending-review'
    | '/profile'
    | '/rejected'
    | '/reset-password'
    | '/rooms/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/complete-profile'
    | '/pending-review'
    | '/profile'
    | '/rejected'
    | '/reset-password'
    | '/rooms/$roomId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/complete-profile'
    | '/pending-review'
    | '/profile'
    | '/rejected'
    | '/reset-password'
    | '/rooms/$roomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CompleteProfileRoute: typeof CompleteProfileRoute
  PendingReviewRoute: typeof PendingReviewRoute
  ProfileRoute: typeof ProfileRoute
  RejectedRoute: typeof RejectedRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RoomsRoomIdRoute: typeof RoomsRoomIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rejected': {
      id: '/rejected'
      path: '/rejected'
      fullPath: '/rejected'
      preLoaderRoute: typeof RejectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending-review': {
      id: '/pending-review'
      path: '/pending-review'
      fullPath: '/pending-review'
      preLoaderRoute: typeof PendingReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete-profile': {
      id: '/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof CompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$roomId': {
      id: '/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof RoomsRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CompleteProfileRoute: CompleteProfileRoute,
  PendingReviewRoute: PendingReviewRoute,
  ProfileRoute: ProfileRoute,
  RejectedRoute: RejectedRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RoomsRoomIdRoute: RoomsRoomIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
